name: test-environment
dependencies:
  - bats 
  - r-cairo 
  - r-hash=2.2.6.1 
  - r-foreach
  - r-rjson
  - r-doparallel
  - r-matrixstats
  - bioconductor-onassis 
  - openjdk=8.0.152 
  - r-reshape2=1.4.3 
  - r-data.table=1.12.8 
  - r-optparse 
  - r-workflowscriptscommon 
  - bats 
  - r-stringi 
  - dropletutils-scripts
